name: 'Upload artifact - customUbuntu'
on:
  workflow_dispatch:

jobs:
  archiveFile:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Write Content'
        uses: Sammamus/test-custom-user-ubuntu-action@main

      - name: 'Archive artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'testCustomUserUbuntuArchive.txt'
          path: 'testCustomUserUbuntuArchive.txt'



